### ISSUE TITLE
lambd in grl layer

### ISSUE THREAD

**Issue by momentum-coding** [lingeringlight/DomainDrop#1]
if gradient from domain discriminator is truncated,why lambd is not 0 but 0.25.

**Comment by lingeringlight** [comment]
Hello, thanks for your attention to our work.
In this work, since we aim to employ a domain discriminator to distinguish and remove domain-sensitive channels, we introduce the GRL to truncate  the impact of the domain discrimination loss on the main network.
Nevertheless, we observe that simply dropping domain-sensitive channels during training could potentially impede the model's learning of these channels, resulting in the retention of specific domain-related features.
Hence, we consider using GRL with the lambd larger than 0, which could further optimize the "dropped" domain-sensitive channels to fully suppress the remaining domain-specific information. The details have also been elaborated in the paper.
 
Thank you once again for your question.
